#!/usr/bin/env python3
"""
Sample from the fine-tuned m2-qwen3-4b-sft checkpoint on Tinker.
Usage: python3 sample_m2_model.py
"""

import asyncio
import os
import tinker
from tinker_cookbook.renderers import get_renderer

API_KEY = os.environ.get("TINKER_API_KEY", "tml-gnnuOReXJScfM3VqO62Rt9yVagpGPQQneb2ZQ9iYhw310e4QB4HUMf0ReHMrxlQTQAAAA")
CHECKPOINT_NAME = "m2-qwen3-4b-codegen-v1"
BASE_MODEL = "Qwen/Qwen3.5-4B"

SYSTEM_PROMPT = (
    "You are an expert Macaulay2 programmer. "
    "Given an algebra problem or question described in natural language, "
    "write correct Macaulay2 code to solve it. "
    "Return only the Macaulay2 code, with no explanation or commentary."
)

TEST_QUESTIONS = [
    "Find the Krull dimension of the ideal generated by (x^2 - y, y^2 - 1) in QQ[x,y].",
    "Compute the Gröbner basis of the ideal (x^2 - y*z, y^2 - x*z, z^2 - x*y) in QQ[x,y,z].",
    "Find the primary decomposition of the ideal (x^2, x*y) in QQ[x,y].",
    "Compute the Hilbert series of QQ[x,y,z]/(x^2, y^2, z^2).",
    "Find the free resolution of the ideal (x^2, x*y, y^2) in QQ[x,y] and display its Betti table.",
    "Compute the radical of the ideal (x^3, x^2*y) in QQ[x,y].",
    "Find the intersection of the ideals (x^2, y) and (x, y^2) in QQ[x,y].",
    "Compute the saturation of the ideal (x^2*y, x*y^2) with respect to (x*y) in QQ[x,y].",
]


async def main():
    print(f"Connecting to Tinker checkpoint '{CHECKPOINT_NAME}'...")
    sc = tinker.ServiceClient(api_key=API_KEY)

    # Find the sampler tinker:// path by name from the user checkpoint list
    rest = sc.create_rest_client()
    ckpts_resp = await rest.list_user_checkpoints_async()
    sampler_name = f"{CHECKPOINT_NAME}-sampler"
    model_path = None
    for ckpt in ckpts_resp.checkpoints:
        if ckpt.checkpoint_id.endswith(sampler_name) or ckpt.checkpoint_id.endswith(CHECKPOINT_NAME):
            model_path = ckpt.tinker_path
            break
    if not model_path:
        raise RuntimeError(
            f"Could not find checkpoint '{sampler_name}' in user checkpoints. "
            "Re-run fine_tune_qwen.py to save fresh weights, or set MODEL_PATH manually."
        )
    print(f"Using checkpoint: {model_path}")
    sampling_client = await sc.create_sampling_client_async(model_path=model_path)
    tokenizer = sampling_client.get_tokenizer()
    renderer = get_renderer("qwen3_5_disable_thinking", tokenizer)
    stop_sequences = renderer.get_stop_sequences()
    params = tinker.SamplingParams(max_tokens=400, temperature=0.1, stop=stop_sequences)

    print(f"Connected.\n{'=' * 70}")

    for i, question in enumerate(TEST_QUESTIONS, 1):
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": question},
        ]
        prompt_str = renderer.build_generation_prompt(messages)

        print(f"[Q{i}] {question}")
        result = await sampling_client.sample_async(
            prompt=prompt_str,
            num_samples=1,
            sampling_params=params,
        )
        parsed = renderer.parse_response(result.sequences[0].tokens)
        if isinstance(parsed, tuple):
            response = parsed[0].get("content", str(parsed[0]))
        else:
            response = parsed
        print(f"[A{i}]\n{response}")
        print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
