#!/usr/bin/env python3
"""
Generate natural-language -> Macaulay2 code training data.

Approach:
  1. Programmatically generate (template_question, m2_code) pairs with
     randomized polynomial inputs across ~10 algebraic operation types.
  2. Use Tinker Nemotron-120B to rephrase each template question into
     2-3 natural language variants.
  3. Save combined dataset to macaulay2-examples/m2_code_gen_training.json
     in the 3-turn conversation format expected by fine_tune_qwen.py.

Usage:
    python generate_training_data.py [--variants N] [--dry-run] [--no-tinker]
"""

import argparse
import asyncio
import json
import random
import sys
from pathlib import Path

import tinker
from tinker_cookbook.renderers import get_renderer

ROOT = Path(__file__).parent.parent
OUTPUT_PATH = ROOT / "macaulay2-examples" / "m2_code_gen_training.json"

TINKER_API_KEY = "tml-gnnuOReXJScfM3VqO62Rt9yVagpGPQQneb2ZQ9iYhw310e4QB4HUMf0ReHMrxlQTQAAAA"
ANNOTATION_MODEL = "Qwen/Qwen3-30B-A3B-Instruct-2507"
ANNOTATION_RENDERER = "qwen3_instruct"

SYSTEM_PROMPT = (
    "You are an expert Macaulay2 programmer. "
    "Given an algebra problem or question described in natural language, "
    "write correct Macaulay2 code to solve it. "
    "Return only the Macaulay2 code, with no explanation or commentary."
)

REPHRASE_SYSTEM = (
    "You rephrase math questions. "
    "Given a template question about a computational algebra problem in Macaulay2, "
    "produce exactly N natural-language rephrasing variants. "
    "Vary the phrasing style: formal, informal, terse, verbose. "
    "Do NOT change the mathematical content or the specific values mentioned. "
    "Return only a JSON array of strings — no explanation, no markdown."
)

# ---------------------------------------------------------------------------
# Random polynomial helpers
# ---------------------------------------------------------------------------

VARS_SMALL = [["x", "y"], ["x", "y", "z"], ["a", "b", "c"], ["s", "t"], ["u", "v", "w"]]
VARS_SINGLE = ["x", "t", "u"]
FIELDS = ["QQ", "ZZ/2", "ZZ/3", "ZZ/5", "ZZ/7", "ZZ/11", "GF(4)", "GF(8)"]
FIELDS_MAIN = ["QQ", "QQ", "QQ", "ZZ/2", "ZZ/5"]  # weighted toward QQ


def rfield():
    return random.choice(FIELDS_MAIN)


def rvars():
    return random.choice(VARS_SMALL)


def rvar():
    return random.choice(VARS_SINGLE)


def rpoly(variables, max_degree=3, max_terms=3, coeff_range=5):
    """Return a random polynomial string in the given variables."""
    terms = []
    n_terms = random.randint(1, max_terms)
    for _ in range(n_terms):
        coeff = random.randint(-coeff_range, coeff_range)
        if coeff == 0:
            coeff = 1
        parts = []
        all_zero = True
        for v in variables:
            exp = random.randint(0, max_degree)
            if exp > 0:
                all_zero = False
                parts.append(f"{v}^{exp}" if exp > 1 else v)
        mono = "*".join(parts) if parts else "1"
        if all_zero:
            # constant term
            terms.append(str(coeff))
        elif coeff == 1:
            terms.append(mono)
        elif coeff == -1:
            terms.append(f"-{mono}")
        else:
            terms.append(f"{coeff}*{mono}")
    # deduplicate by rebuilding
    return " + ".join(terms).replace("+ -", "- ")


def rpolys(variables, n, **kwargs):
    return [rpoly(variables, **kwargs) for _ in range(n)]


def ring_decl(field, variables):
    return f"R = {field}[{', '.join(variables)}]"


def ideal_decl(polys):
    return f"I = ideal({', '.join(polys)})"


# ---------------------------------------------------------------------------
# Programmatic generators — each returns list of (template_question, m2_code)
# ---------------------------------------------------------------------------

def gen_dimension(n=50):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(1, 3)
        polys = rpolys(variables, n_gens)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\ndim I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        field_name = {"QQ": "rationals", "ZZ/2": "GF(2)", "ZZ/3": "GF(3)",
                      "ZZ/5": "GF(5)", "ZZ/7": "GF(7)", "ZZ/11": "GF(11)"}.get(field, field)
        q = (f"Find the Krull dimension of the ideal generated by ({poly_str}) "
             f"in {field_name}[{var_str}].")
        examples.append((q, code, "dimension"))
    return examples


def gen_degree(n=40):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(1, 3)
        polys = rpolys(variables, n_gens)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\ndegree I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the degree of the variety defined by ({poly_str}) "
             f"in {field}[{var_str}].")
        examples.append((q, code, "degree"))
    return examples


def gen_dim_and_degree(n=30):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(1, 3)
        polys = rpolys(variables, n_gens)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\n(dim I, degree I)"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute both the dimension and degree of the ideal ({poly_str}) "
             f"in {field}[{var_str}].")
        examples.append((q, code, "dimension"))
    return examples


def gen_groebner(n=50):
    examples = []
    orders = [("lex", "lex"), ("grevlex", "graded reverse lex"), ("", "default")]
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(2, 3)
        polys = rpolys(variables, n_gens)
        order_m2, order_name = random.choice(orders)
        if order_m2:
            ring = f"R = {field}[{', '.join(variables)}, MonomialOrder => {order_m2}]"
        else:
            ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\ngroebnerBasis I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the Gröbner basis of the ideal ({poly_str}) "
             f"in {field}[{var_str}].")
        examples.append((q, code, "groebner_basis"))
    return examples


def gen_primary_decomposition(n=40):
    examples = []
    for _ in range(n):
        field = "QQ"  # primary decomp usually over QQ
        variables = rvars()
        n_gens = random.randint(2, 3)
        polys = rpolys(variables, n_gens, max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nprimaryDecomposition I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Find the primary decomposition of the ideal ({poly_str}) in QQ[{var_str}].")
        examples.append((q, code, "primary_decomposition"))
    return examples


def gen_associated_primes(n=30):
    examples = []
    for _ in range(n):
        field = "QQ"
        variables = rvars()
        n_gens = random.randint(2, 3)
        polys = rpolys(variables, n_gens, max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nassociatedPrimes I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"List the associated primes of the ideal ({poly_str}) in QQ[{var_str}].")
        examples.append((q, code, "primary_decomposition"))
    return examples


def gen_radical(n=40):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(1, 3)
        polys = rpolys(variables, n_gens, max_degree=3)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nradical I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the radical of the ideal ({poly_str}) in {field}[{var_str}].")
        examples.append((q, code, "radical"))
    return examples


def gen_hilbert_series(n=40):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        n_gens = random.randint(1, 3)
        polys = rpolys(variables, n_gens, max_degree=3)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nS = R/I\nhilbertSeries S"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the Hilbert series of the ring {field}[{var_str}]/({poly_str}).")
        examples.append((q, code, "hilbert"))
    return examples


def gen_free_resolution(n=40):
    examples = []
    for _ in range(n):
        field = "QQ"
        variables = rvars()
        n_gens = random.randint(2, 4)
        polys = rpolys(variables, n_gens, max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nresolution I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the minimal free resolution of the ideal ({poly_str}) in QQ[{var_str}].")
        examples.append((q, code, "free_resolution"))
    return examples


def gen_betti(n=30):
    examples = []
    for _ in range(n):
        field = "QQ"
        variables = rvars()
        n_gens = random.randint(2, 4)
        polys = rpolys(variables, n_gens, max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nbetti res I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Find the Betti table of the ideal ({poly_str}) in QQ[{var_str}].")
        examples.append((q, code, "free_resolution"))
    return examples


def gen_saturation(n=30):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        polys = rpolys(variables, 2, max_degree=2)
        sat_poly = rpoly(variables, max_degree=2, max_terms=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = (f"{ring}\n{ideal}\n"
                f"J = ideal({sat_poly})\n"
                f"saturate(I, J)")
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Saturate the ideal ({poly_str}) with respect to ({sat_poly}) "
             f"in {field}[{var_str}].")
        examples.append((q, code, "saturation"))
    return examples


def gen_ideal_quotient(n=30):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        polys1 = rpolys(variables, 2, max_degree=2)
        polys2 = rpolys(variables, 1, max_degree=2)
        ring = ring_decl(field, variables)
        code = (f"{ring}\n"
                f"I = ideal({', '.join(polys1)})\n"
                f"J = ideal({', '.join(polys2)})\n"
                f"I : J")
        var_str = ", ".join(variables)
        q = (f"Compute the ideal quotient ({', '.join(polys1)}) : ({', '.join(polys2)}) "
             f"in {field}[{var_str}].")
        examples.append((q, code, "ideal_operations"))
    return examples


def gen_intersection(n=30):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        polys1 = rpolys(variables, 2, max_degree=2)
        polys2 = rpolys(variables, 2, max_degree=2)
        ring = ring_decl(field, variables)
        code = (f"{ring}\n"
                f"I = ideal({', '.join(polys1)})\n"
                f"J = ideal({', '.join(polys2)})\n"
                f"intersect(I, J)")
        var_str = ", ".join(variables)
        q = (f"Find the intersection of the ideals ({', '.join(polys1)}) and "
             f"({', '.join(polys2)}) in {field}[{var_str}].")
        examples.append((q, code, "ideal_operations"))
    return examples


def gen_minimal_primes(n=30):
    examples = []
    for _ in range(n):
        field = "QQ"
        variables = rvars()
        polys = rpolys(variables, 2, max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nminimalPrimes I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Find the minimal primes of the ideal ({poly_str}) in QQ[{var_str}].")
        examples.append((q, code, "primary_decomposition"))
    return examples


def gen_ring_construction(n=30):
    """Ring quotients and explicit ring constructions."""
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        polys = rpolys(variables, random.randint(1, 3), max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\nS = R/I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Define the quotient ring {field}[{var_str}]/({poly_str}).")
        examples.append((q, code, "ring_construction"))
    return examples


def gen_projective_dimension(n=20):
    examples = []
    for _ in range(n):
        field = "QQ"
        variables = rvars()
        polys = rpolys(variables, random.randint(2, 3), max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\npdim comodule I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Compute the projective dimension of QQ[{var_str}]/({poly_str}).")
        examples.append((q, code, "homological"))
    return examples


def gen_codimension(n=20):
    examples = []
    for _ in range(n):
        field = rfield()
        variables = rvars()
        polys = rpolys(variables, random.randint(1, 3), max_degree=2)
        ring = ring_decl(field, variables)
        ideal = ideal_decl(polys)
        code = f"{ring}\n{ideal}\ncodim I"
        poly_str = ", ".join(polys)
        var_str = ", ".join(variables)
        q = (f"Find the codimension of the ideal ({poly_str}) in {field}[{var_str}].")
        examples.append((q, code, "dimension"))
    return examples


def generate_all_templates():
    """Generate all (question, code, category) triples."""
    all_examples = []
    generators = [
        gen_dimension,
        gen_degree,
        gen_dim_and_degree,
        gen_groebner,
        gen_primary_decomposition,
        gen_associated_primes,
        gen_radical,
        gen_hilbert_series,
        gen_free_resolution,
        gen_betti,
        gen_saturation,
        gen_ideal_quotient,
        gen_intersection,
        gen_minimal_primes,
        gen_ring_construction,
        gen_projective_dimension,
        gen_codimension,
    ]
    for gen_fn in generators:
        batch = gen_fn()
        all_examples.extend(batch)
        print(f"  {gen_fn.__name__}: {len(batch)} examples")
    print(f"  Total templates: {len(all_examples)}")
    return all_examples


# ---------------------------------------------------------------------------
# Tinker Nemotron annotation
# ---------------------------------------------------------------------------

async def rephrase_question(sampling_client, renderer, question: str, n_variants: int) -> list[str]:
    """Ask Nemotron to rephrase a template question into n natural variants."""
    user_msg = (
        f"Rephrase the following math question into {n_variants} natural language variants. "
        f"Keep the same mathematical content and specific values. "
        f"Return a JSON array of {n_variants} strings only.\n\n"
        f"Question: {question}"
    )
    messages = [
        {"role": "system", "content": REPHRASE_SYSTEM},
        {"role": "user", "content": user_msg},
    ]
    prompt_str = renderer.build_generation_prompt(messages)
    stop_sequences = renderer.get_stop_sequences()
    params = tinker.SamplingParams(max_tokens=512, temperature=0.7, stop=stop_sequences)

    try:
        result = await sampling_client.sample_async(
            prompt=prompt_str,
            num_samples=1,
            sampling_params=params,
        )
        parsed = renderer.parse_response(result.sequences[0].tokens)
        if isinstance(parsed, tuple):
            text = parsed[0].get("content", "")
        else:
            text = str(parsed)

        # Extract JSON array
        text = text.strip()
        start = text.find("[")
        end = text.rfind("]") + 1
        if start >= 0 and end > start:
            variants = json.loads(text[start:end])
            if isinstance(variants, list) and all(isinstance(v, str) for v in variants):
                return variants[:n_variants]
    except Exception as e:
        print(f"    WARN rephrase failed: {e}", file=sys.stderr)

    return [question]  # fall back to original


async def annotate_with_tinker(templates: list[tuple], n_variants: int) -> list[dict]:
    """Use Nemotron to generate n_variants phrasings for each template question."""
    sc = tinker.ServiceClient(api_key=TINKER_API_KEY)

    print(f"\nConnecting to Tinker ({ANNOTATION_MODEL})...")
    sampling_client = await sc.create_sampling_client_async(base_model=ANNOTATION_MODEL)
    tokenizer = sampling_client.get_tokenizer()
    renderer = get_renderer(ANNOTATION_RENDERER, tokenizer)
    print("Connected.\n")

    records = []
    total = len(templates)
    for i, (question, code, category) in enumerate(templates):
        if (i + 1) % 25 == 0 or i == 0:
            print(f"  [{i+1}/{total}] annotating...")

        variants = await rephrase_question(sampling_client, renderer, question, n_variants)

        for variant in variants:
            records.append({
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": variant},
                    {"role": "assistant", "content": code},
                ],
                "metadata": {
                    "source": "programmatic",
                    "category": category,
                    "template_question": question,
                    "verified": False,
                },
            })

    return records


def build_records_no_tinker(templates: list[tuple]) -> list[dict]:
    """Build records using only template questions (no Tinker annotation)."""
    records = []
    for question, code, category in templates:
        records.append({
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": question},
                {"role": "assistant", "content": code},
            ],
            "metadata": {
                "source": "programmatic",
                "category": category,
                "template_question": question,
                "verified": False,
            },
        })
    return records


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Generate M2 code-generation training data")
    p.add_argument(
        "--variants",
        type=int,
        default=2,
        help="Question phrasings per template via Nemotron (default: 2)",
    )
    p.add_argument(
        "--no-tinker",
        action="store_true",
        help="Skip Tinker annotation and use template questions directly",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Show stats without generating or calling Tinker",
    )
    return p.parse_args()


async def main_async(args):
    print("Generating template examples...")
    templates = generate_all_templates()

    if args.dry_run:
        print(f"\n-- Dry run --")
        print(f"Templates: {len(templates)}")
        print(f"Variants per template: {args.variants if not args.no_tinker else 1}")
        est = len(templates) if args.no_tinker else len(templates) * args.variants
        print(f"Estimated output records: {est}")
        print(f"\nSample template:")
        q, code, cat = templates[0]
        print(f"  Category: {cat}")
        print(f"  Question: {q}")
        print(f"  Code:\n    {code.replace(chr(10), chr(10) + '    ')}")
        return

    if args.no_tinker:
        print("Building records without Tinker annotation...")
        records = build_records_no_tinker(templates)
    else:
        records = await annotate_with_tinker(templates, args.variants)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(records, f, indent=2)
    print(f"\nSaved {len(records)} training records to {OUTPUT_PATH}")


def main():
    args = parse_args()
    asyncio.run(main_async(args))


if __name__ == "__main__":
    main()
